# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__

'1.19.5'

In [ ]:
np.__config__.show()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
a.size

10

In [ ]:
a.itemsize

8

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
v=np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
v=np.arange(10,50)
v=v[::-1]
v

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
m=np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
b=np.nonzero([1,2,0,0,4,0])
b

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x=np.random.random((3,3,3))
x

array([[[0.88943477, 0.18701001, 0.02732633],
        [0.51917417, 0.2779992 , 0.28818496],
        [0.82430616, 0.81140892, 0.54592372]],

       [[0.72258821, 0.71767746, 0.86913208],
        [0.21555978, 0.98016513, 0.50781094],
        [0.22677018, 0.79546161, 0.87929303]],

       [[0.7295704 , 0.55491297, 0.90367364],
        [0.10421596, 0.82477075, 0.02871057],
        [0.89900188, 0.13607988, 0.72044739]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x=np.random.random((10,10))
x.min(),x.max()


(0.008930582892003214, 0.9963412164428922)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x=np.random.random(30)
x.mean()

0.5250053333391053

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x=np.ones((10,10))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x=np.ones((5,5))
x=np.pad(x,pad_width=1,constant_values=0)
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

nan
False
False
nan 
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
x=np.diag(1+np.arange(4),k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
x=np.unravel_index(100,(6,7,8))
x

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
array=np.array([[0,1],[1,0]])
y=np.tile(array,(4,4))
y

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x=np.random.random((5,5))
max,min=x.max(),x.min()
x=(x-min)/(max-min)
x


array([[0.18637478, 0.61022784, 0.27078526, 0.04558725, 0.19548313],
       [0.5816367 , 0.43938075, 0.68594245, 0.4848034 , 0.15788867],
       [0.        , 0.80211922, 0.13246163, 0.66727923, 0.75260523],
       [0.5715643 , 0.70057658, 0.30311175, 0.54337999, 0.53542044],
       [0.03063313, 0.89874976, 1.        , 0.9184168 , 0.6351747 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color=np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x= np.dot(np.ones((5,3)), np.ones((3,2)))
x

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x= np.arange(11)
x[(3 < x) & (x<= 8)] *= -1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))      
from numpy import *             #9
print(sum(range(5),-1))         #10
```

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(5)
Z ** Z       # = [1, 1, 4, 27, 256]
2 << Z >> 2  # = [0, 1, 2, 4, 8]
Z < - Z      # = [False, False, False, False, False]
1j * Z       # = [0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j]
Z / 1 / 1    # = [0., 1., 2., 3., 4.]
Z < Z > Z    # ValueError

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)                            # = nan
np.array(0) // np.array(0)                           # = 0 
np.array([np.nan]).astype(int).astype(float)         # = [-9.22337204e+18]

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x= np.random.uniform(-10,+10,10)
np.copysign(np.ceil(np.abs(x)),x)

array([ -6.,  -3.,   9.,   1.,   1.,  -3., -10.,  -3.,   3.,  -3.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)

array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
x=np.seterr(all="ignore")
x
#y=np.errstate(divide="ignore")
#y

{'divide': 'ignore', 'invalid': 'ignore', 'over': 'ignore', 'under': 'ignore'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)             #False
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2022-02-03
2022-02-04
2022-02-05


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
x = np.arange('2016-05', '2016-06', dtype='datetime64[D]')
x

array(['2016-05-01', '2016-05-02', '2016-05-03', '2016-05-04',
       '2016-05-05', '2016-05-06', '2016-05-07', '2016-05-08',
       '2016-05-09', '2016-05-10', '2016-05-11', '2016-05-12',
       '2016-05-13', '2016-05-14', '2016-05-15', '2016-05-16',
       '2016-05-17', '2016-05-18', '2016-05-19', '2016-05-20',
       '2016-05-21', '2016-05-22', '2016-05-23', '2016-05-24',
       '2016-05-25', '2016-05-26', '2016-05-27', '2016-05-28',
       '2016-05-29', '2016-05-30', '2016-05-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.negative(A,out=A)
np.multiply(A,B,out=A)
np.divide(A,2,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[2. 1. 1. 3. 2. 5. 0. 7. 8. 7.]
[2. 1. 1. 3. 2. 5. 0. 7. 8. 7.]
[2. 1. 1. 3. 2. 5. 0. 7. 8. 7.]
[2 1 1 3 2 5 0 7 8 7]
[2. 1. 1. 3. 2. 5. 0. 7. 8. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x = np.zeros((5,5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
y = np.fromiter(generate(),dtype=float,count=-1)
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x=np.random.random(10)
x.sort()
x

array([0.08152759, 0.09568084, 0.37903738, 0.4676568 , 0.63694469,
       0.66018721, 0.66888256, 0.76379631, 0.7898465 , 0.85570321])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
x=np.arange(11)
x=np.add.reduce(x)
x

55

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.random(10)
B = np.random.random(10)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
equal

False


False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.02174772 0.31899647 0.97259541 0.28823553 1.09683244 0.91753359
 0.38923013 1.18193368 1.00063675 1.2299312 ]
[0.27768797 0.9248237  1.44819859 0.77713051 0.80732556 1.21704526
 0.60989337 0.85042982 0.94043699 0.75822142]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x=np.random.random(10)
x[x.argmax()]=0
x

array([0.56526302, 0.48645588, 0.78044593, 0.13043899, 0.65290118,
       0.566526  , 0.72893498, 0.60231601, 0.        , 0.52828661])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
x = np. zeros((16,16))
np. set_printoptions(threshold=np. inf)
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

94


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
x=np.zeros(10,[('position',[('x',float,1),('y',float,1)]),
               ('color',[('r',float,1),('g',float,1),('b',float,1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.50570866 0.44123355 0.61662426 0.62541968 0.33487975
  0.45705063 0.37771026 0.60646331 0.40287068]
 [0.50570866 0.         0.85109004 0.68544093 0.92212563 0.80052466
  0.17179444 0.18941663 0.86387066 0.29025762]
 [0.44123355 0.85109004 0.         1.03824218 0.94310975 0.54660952
  0.86262436 0.78389456 0.9543129  0.83470067]
 [0.61662426 0.68544093 1.03824218 0.         0.36539663 0.58765855
  0.51415225 0.51336294 0.28561011 0.39932107]
 [0.62541968 0.92212563 0.94310975 0.36539663 0.         0.399875
  0.76832889 0.73274457 0.07980537 0.6423019 ]
 [0.33487975 0.80052466 0.54660952 0.58765855 0.399875   0.
  0.70146293 0.6332747  0.42286536 0.60079618]
 [0.45705063 0.17179444 0.86262436 0.51415225 0.76832889 0.70146293
  0.         0.07994177 0.70548892 0.12619548]
 [0.37771026 0.18941663 0.78389456 0.51336294 0.73274457 0.6332747
  0.07994177 0.         0.67519886 0.11548385]
 [0.60646331 0.86387066 0.9543129  0.28561011 0.07980537 0.42286536
  0.70548892 0.67519886

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
x=np.arange(10,dtype=np.float32)
x=x.astype(np.int32,copy=False)
print(x)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s,delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x,y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
z=np.sqrt(x*x+y*y)
sigma,mu=1.0,0.0
a=np.exp(-((z-mu)**2/(2.0*sigma**2)))
print(a)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
a = 10
b = 3
c = np.zeros((a,a))
np.put(c, np.random.choice(range(a*a), b, replace=False),1)
print(c)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
y

array([[ 0.34685449, -0.36005602, -0.36530931, -0.2579168 ,  0.39313259,
         0.01206913,  0.31958095, -0.08362899,  0.15520072, -0.15992675],
       [-0.01910616,  0.16766074,  0.04495377, -0.33094105, -0.12338635,
        -0.32547849, -0.27438559,  0.41418796,  0.33523061,  0.11126458],
       [ 0.38743307, -0.23085247,  0.10689307,  0.01079388, -0.47906074,
         0.00415767,  0.26421186, -0.07556425, -0.02311927,  0.03510718],
       [-0.07282165,  0.06454364,  0.56853668,  0.04861922, -0.25623687,
         0.13611875, -0.01104056,  0.01372332, -0.14716657, -0.34427596],
       [-0.01592377, -0.09094928,  0.25698278, -0.1295133 , -0.00382434,
         0.08904051,  0.09836828, -0.14881826, -0.04198963, -0.01337298]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
x=np.random.randint(0,10,(3,3))
print(x[x[:,1].argsort()])

[[9 0 6]
 [2 3 1]
 [2 4 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
x=np.random.uniform(0,1,10)
y=0.5
z=x.flat[np.abs(x-y).argmin()]
z

0.520048687977312

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
a=np.ones(10)
b=np.random.randint(0,len(a),20)
np.add.at(a,b,1)
print(a)

[1. 3. 4. 3. 2. 4. 1. 4. 4. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X=[1,2,3,4,5,6]
I=[1,3,9,3,4,1]
F=np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[75 51 68 41]
 [50 57 58 52]
 [48 45 59 45]]
[[75 51 68 41]
 [50 57 58 52]
 [48 45 59 45]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.4645344  0.48790338 0.51347274 0.43492111 0.43119835 0.71489135
 0.44432503 0.41765371 0.55688143 0.54852084]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [3]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(0,10,(3,3))
np.diag(np.dot(a,b))

array([64, 16, 50])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [9]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [10]:
a=np.ones((5,5,3))
b=2*np.ones((5,5))
print(a*b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [11]:
a=np.arange(25).reshape(5,5)
a[[0,1]]=a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [12]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 43) ( 4, 75) ( 9, 19) ( 9, 66) (10, 35) (10, 65) (11, 14) (11, 47)
 (14, 23) (14, 34) (14, 47) (19, 66) (23, 34) (29, 54) (29, 84) (31, 35)
 (31, 89) (35, 57) (35, 65) (35, 89) (35, 91) (37, 58) (37, 59) (43, 75)
 (47, 62) (47, 91) (54, 84) (57, 91) (58, 59) (62, 91)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [13]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [14]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [15]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [16]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.11852524,  0.00166346,  0.19460029, -0.1442101 ,  0.18897239,
       -0.74106828, -0.56928283, -0.3114227 ,  0.376351  , -0.93670878,
       -0.18271703,  0.03298524, -0.02070652,  0.69653099,  0.91058057,
        0.93277052, -0.43990805, -0.90026377,  0.15187706, -0.81483802,
       -0.70740552, -0.27123075, -0.61885144,  0.39249018, -0.41820627,
       -0.85477725, -0.53632128, -0.43004227, -0.38882406,  0.90719777,
       -0.50527545,  0.08495949,  0.31339535,  0.49091296,  0.25825481,
       -0.11369704,  0.44991909,  0.7552342 ,  0.12672469, -0.41939398,
       -0.93176961,  0.27328615, -0.61317076, -0.7071114 ,  0.09256672,
        0.2603303 , -0.47149426,  0.28506504,  0.92579939, -0.31905595,
       -0.43802876, -0.51884657,  0.98437511,  0.92548779,  0.60568733,
       -0.9577542 , -0.94320106, -0.51667781, -0.95623241, -0.57748648,
       -0.31778347,  0.53771548, -0.43744313,  0.41882452, -0.55386447,
        0.45344474,  0.05451478, -0.27206728, -0.26859615, -0.95

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [18]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
    
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 3.20437983  5.94948887  1.78568168  5.23749136  5.0554595   4.35926365
  4.73538611 13.49451512 12.26114293  5.76493971]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [19]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.4751424   7.4555322   0.61816332 10.1719081   7.5182001   6.66379953
   5.72145921  8.16768959  4.21140042 10.63293232]
 [ 9.82822656  8.05030502  8.10544277  3.00094856  4.44063661  0.55975594
   4.74256741  1.38165115  1.84947573  3.19244576]
 [ 2.5021104   4.0366277   9.01245674 14.54993048  7.43015964 14.67837725
   3.67027343 12.06868018  7.25820149 15.35762426]
 [ 2.21000204  2.38716913  1.26827426  2.02438872  2.74904368 10.86356928
   4.50838294  0.375591    4.92428052  2.80605769]
 [ 2.18979838  1.4100301   5.50753385  9.12976956  3.12391541 12.84693683
   0.26389981  6.69581847  2.01924698  9.91707347]
 [ 6.92036029  6.82940855  4.53277509  0.96900058  6.11772789 15.14352995
   8.57896031  1.73310323  6.78500311  1.98096598]
 [ 3.15673456  3.48380851  9.53880179 14.52456317  7.06207768 15.30738271
   3.18579098 12.00072255  7.11808847 15.36437564]
 [ 9.49185093  8.87183108  6.74576107  1.11210027  7.36334814 17.68281565
  10.31955451  1.75851216  7.09829796  2.25046051]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [20]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 3 9 5 4 1 9 2 6 4]
 [6 3 5 7 5 5 2 9 8 7]
 [9 5 0 2 8 5 1 1 3 0]
 [2 8 8 0 1 1 0 5 1 1]
 [9 6 4 4 7 6 8 6 2 1]
 [1 1 9 5 9 2 1 4 8 1]
 [8 8 0 0 4 0 7 6 0 3]
 [3 6 0 7 0 1 0 3 1 2]
 [3 2 9 1 2 5 2 1 6 0]
 [0 2 0 3 5 6 4 3 8 1]]
[[0 0 0 0 0]
 [0 9 3 9 5]
 [0 6 3 5 7]
 [0 9 5 0 2]
 [0 2 8 8 0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [21]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [25]:
a=np.random.uniform(1,0,(10,10))
x,y,z=np.linalg.svd(a)
rank=np.sum(y>1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [27]:
a = np.random.randint(0,10,50)
print(np.bincount(a).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [29]:
a = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (a.shape[0]-3)
j = 1 + (a.shape[1]-3)
C = stride_tricks.as_strided(a, shape=(i, j, n, n), strides=a.strides + a.strides)
print(C)

[[[[1 0 0]
   [2 3 2]
   [1 3 1]]

  [[0 0 3]
   [3 2 2]
   [3 1 0]]

  [[0 3 2]
   [2 2 3]
   [1 0 3]]

  [[3 2 3]
   [2 3 1]
   [0 3 3]]

  [[2 3 1]
   [3 1 2]
   [3 3 3]]

  [[3 1 0]
   [1 2 4]
   [3 3 1]]

  [[1 0 0]
   [2 4 3]
   [3 1 4]]

  [[0 0 3]
   [4 3 0]
   [1 4 4]]]


 [[[2 3 2]
   [1 3 1]
   [2 0 0]]

  [[3 2 2]
   [3 1 0]
   [0 0 4]]

  [[2 2 3]
   [1 0 3]
   [0 4 3]]

  [[2 3 1]
   [0 3 3]
   [4 3 1]]

  [[3 1 2]
   [3 3 3]
   [3 1 4]]

  [[1 2 4]
   [3 3 1]
   [1 4 1]]

  [[2 4 3]
   [3 1 4]
   [4 1 2]]

  [[4 3 0]
   [1 4 4]
   [1 2 4]]]


 [[[1 3 1]
   [2 0 0]
   [1 2 1]]

  [[3 1 0]
   [0 0 4]
   [2 1 1]]

  [[1 0 3]
   [0 4 3]
   [1 1 1]]

  [[0 3 3]
   [4 3 1]
   [1 1 1]]

  [[3 3 3]
   [3 1 4]
   [1 1 2]]

  [[3 3 1]
   [1 4 1]
   [1 2 1]]

  [[3 1 4]
   [4 1 2]
   [2 1 3]]

  [[1 4 4]
   [1 2 4]
   [1 3 0]]]


 [[[2 0 0]
   [1 2 1]
   [2 0 2]]

  [[0 0 4]
   [2 1 1]
   [0 2 0]]

  [[0 4 3]
   [1 1 1]
   [2 0 0]]

  [[4 3 1]
   [1 1 1]
   [0 0 1]]

  [[3 1 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [30]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  9  4  1 10]
 [ 9  0  1 12  7]
 [ 4  1  6 42  3]
 [ 1 12 42  5  3]
 [10  7  3  3  7]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [31]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [33]:
a = np.ones((16,16))
b = 4
S = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], b), axis=0),
                                       np.arange(0, a.shape[1], b), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [35]:
def iterate(z):
  
  n=(z[0:-2,0:-2]+z[0:-2,1:-1]+z[0:-2,2:]+
     z[1:-1,0:-2]             +z[1:-1,2:]+
     z[2:  ,0:-2]+z[2:  ,1:-1]+z[2:  ,2:])
  
  birth=(n==3) & (z[1:-1,1:-1]==0)
  survive=((n==2) | (n==3)) & (z[1:-1,1:-1]==1)
  z[...]=0
  z[1:-1,1:-1][birth | survive]=1
  return z 
  
z=np.random.randint(0,2,(50,50))
for i in range(100):z=iterate(z)
print(z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [37]:
a = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (a[np.argpartition(-a,n)[:n]])

[9995 9999 9998 9997 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [38]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [39]:
a = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
r = np.core.records.fromarrays(a.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(a)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [44]:
Z = np.random.rand(5e7)

%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

TypeError: ignored

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [45]:

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 4 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [51]:
Z = np.random.randint(0,5,(10,3))
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[2 2 4]
 [4 2 3]
 [3 1 4]
 [4 3 0]
 [3 1 0]
 [0 1 4]
 [1 0 0]
 [4 1 0]
 [4 4 1]
 [3 2 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [52]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [54]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [60]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)    

array([[0.19738534, 0.2276944 , 0.33141697, 0.1517357 , 0.09408212,
        0.19067937, 0.32000539, 0.35960729, 0.07026434, 0.12386986],
       [0.46839529, 0.54031869, 0.78645229, 0.36006873, 0.22325682,
        0.45248203, 0.7593726 , 0.85334789, 0.16673723, 0.2939431 ],
       [0.19023091, 0.21944139, 0.31940443, 0.14623589, 0.09067202,
        0.183768  , 0.30840647, 0.34657297, 0.06771754, 0.11938007],
       [0.08272624, 0.09542908, 0.13890029, 0.063594  , 0.03943079,
        0.0799157 , 0.13411757, 0.15071514, 0.02944851, 0.05191514],
       [0.21155422, 0.24403896, 0.35520703, 0.16262772, 0.10083561,
        0.20436688, 0.34297629, 0.38542093, 0.07530811, 0.13276159],
       [0.00289897, 0.00334411, 0.00486747, 0.00222852, 0.00138177,
        0.00280048, 0.00469987, 0.0052815 , 0.00103196, 0.00181926],
       [0.42321845, 0.48820483, 0.71059878, 0.32534002, 0.20172365,
        0.40884003, 0.68613094, 0.77104229, 0.15065539, 0.26559222],
       [0.35367913, 0.40798754, 0.5938397

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [59]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [57]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [58]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.25049103  0.09915855]
